apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscalling
  labels:
    app: autoscalling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscalling
  template:
    metadata:
      labels:
        app: autoscalling
    spec:
      containers:
        - name: autoscalling
          image: shestera/scaletestapp
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "10Mi"
            limits:
              memory: "20Mi"
